### ISSUE TITLE
Pwncat as a Service

### ISSUE THREAD

**Issue by WesVleuten** [calebstewart/pwncat#109]
**Is your feature request related to a problem? Please describe.**
I'd love to be able to setup a listener that's always running in the background and connect to the program once a connection has come in. At the same time I'd like to be able to run a that same program on a vps and connect to the remote listener service, like a proxy for reverse shells or some sort of C2 service.

This could be a great help while doing CTF games.

Maybe it could even give me a notification of a connection through the WM.

**Describe the solution you'd like**
I'd like to run a service on my pc and server that looks at a config file for ports to listen on. Then after a connection has come in it will be able to do some automated tasks if configured and it will just sit there untill I connect to the session.

Idea for config file:
```
# pwncat service config
authentication:
    - westar:helloworld
hosts:
    - 2001:db8:85a3:8d3:1319:8a2e:370:7348
    - 1.1.1.1
ports:
    - 4444
    - 4242
    - 1234
automation:
    windows:
        - persist
    linux:
        - escalate
        - persist
```

Then I could connect to the service with `pwncat pwncat://westar:helloworld@1.1.1.1`, or I could setup the server as a default in a configuration file.

Important note is that it would always use the local environment for files and modules. If I `upload linpeas.sh` it should pick it up from my local machine pass it through the vps/service and then upload it to the target.

**Describe alternatives you've considered**
Ngrok could help with this, but it has it's reliability issues and it wouldn't give the always on feature.

**Additional context**
I'd love to work on this, but I want to hear your opinion on this before I start.
